config/routes.rb
CoderXCoder::Application.routes.draw do
  
  devise_for :users
  resources :users
  resources :profiles
  
  resources :notifications
  
  resources :users do
    resources :topics
    resources :notifications
    resources :comments
  end
  
  resources :topics do
    resources :comments
  end  
  
  root to: 'static_pages#home'  

end

app/models/topic.rb
class Topic < ActiveRecord::Base

  attr_accessible :title, :content, :hits
  belongs_to :user
  
  has_many :comments, dependent: :destroy
  has_many :notifications, :as => :notifiable, :dependent => :destroy  
  
  validates :title, presence: true, length: { maximum: 120 }
  validates :user_id, presence: true
  
  scope :last_actived, order("topics.commented_at DESC, topics.created_at DESC")

  before_save :set_last_commented_at

  def set_last_commented_at
    self.commented_at = Time.now
  end

  def update_last_commented_at
    set_last_commented_at
    self.save
  end
  
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  before_filter :authenticate_user!, :except => [:show, :index]
  
  def index
    @topics = Topic.last_actived.paginate(page: params[:page])
  end
  
  def new
    @topic = Topic.new
  end
  
  def create
    @topic = current_user.topics.build(params[:topic])
    if @topic && @topic.save
      flash[:success] = "Topic have been posted."
      redirect_to topic_path @topic
    else
      render 'new'
    end
  end
  
  def show
    @topic = Topic.find(params[:id])
    @comments = @topic.comments.order('created_at ASC').paginate(page: params[:page])
    @page = params[:page]
    @page ||= 1;
  end
  
  def edit
    @topic = Topic.find(params[:id])
  end
  
  def update
    @topic = Topic.find(params[:id])
    if @topic && @topic.update_attributes(params[:topic])
      flash[:success] = "Topic updated."
      redirect_to topic_path @topic
    else
      render 'edit'
    end
  end
  
  def destroy
    @topic = Topic.find(params[:id])
    if @topic.destroy
      flash[:success] = "Topic deleted."
      redirect_to topics_path
    else
      render 'edit'
    end
  end  
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_commented_topic.html.erb
<li>
	<%= link_to commented_topic.title, commented_topic %>
</li>

app/views/topics/_created_topic.html.erb
<li>
	<%= link_to created_topic.title, created_topic %>
</li>

app/views/topics/_topic.html.erb
<div class="cell bottomborder topiccell">
	<table>
		<tbody>
			<tr>
				<td>
					<div class="gravatar">
						 <%= link_to gravatar_for(topic.user), topic.user %>
					</div>
				</td>
				<td>
					<div class="topic-title"><%= link_to topic.title, topic %></div>
					<div class="separator7"></div>
					<div class="topic-info">
					  <span class="grayfont link">
							<%= link_to topic.user.username, topic.user %>
						</span>
						<%= "posted #{time_ago_in_words(topic.created_at)} ago. #{pluralize(topic.comments_count, "comment")}. " %>
					</div>
				</td>
			</tr>
		</tbody>
	</table>
</div>

app/views/topics/_topic_form.html.erb
<%= form_for(@topic) do |f| %>


	<div class="inner bottomborder">
		<h3><%= locals[:info_title] %>
			<%= f.submit locals[:action_btn_title], class: "btn btn-post-topic" %>
		</h3>
	</div>
	<div class="inner bottomborder">
		<%= render 'shared/error_messages', object: f.object %>
	
		<%= f.text_field :title, class: "input-topic-title", placeholder: "Title" %>
		<%= f.text_area :content, class: "input-topic-content", placeholder: "Content" %>
	</div>
<% end %>
<div class="h-inner">
	<div class="grayfont link">
		<p><strong>Tips:</strong></p>
		<ul>
			<li>content can be empty.</li>
			<li>support <a href="http://daringfireball.net/projects/markdown/syntax" target="_blank" title="Markdown Syntax Documentation">markdown syntax.</a></li>
		</ul>
	</div>
</div>

app/views/topics/edit.html.erb
<% provide :title, "Edit Post" %>

<div class="rect">
	<%= render 'topic_form', locals: { info_title: "Edit Topic", action_btn_title: "Update Topic" } %>
</div>

app/views/topics/index.html.erb
<div class="rect">
	<div class="inner bottomborder">
		<h3>Recent Topics
			<%= link_to "New Topic", new_topic_path, class: "btn btn-new-topic" %>
		</h3>
	</div>
	<div class="h-inner">
		<% if @topics.any? %>
			<%= render partial: 'topic', collection: @topics %>
			<%= will_paginate @topics %>
		<% end %>			
	</div>
</div>

app/views/topics/new.html.erb
<% provide :title, "New Post" %>

<div class="rect">
	<%= render 'topic_form', locals: { info_title: "New Topic", action_btn_title: "Post Topic" } %>
</div>

app/views/topics/show.html.erb
<% provide :title, @topic.title %>

<div class="rect">
	
<% if @topic.content.empty? %>
	<div class="inner">
<% else %>
	<div class="inner bottomborder">
<% end %>
		<table>
			<tbody>
				<tr>
					<td>
						<div class="gravatar">
							 <%= link_to gravatar_for(@topic.user), @topic.user %>
						</div>
					</td>
					<td>
						<div class="topic-title"><%= @topic.title %></div>
						<div class="separator7"></div>
						<div class="topic-info">
						  <span class="grayfont link">
								<%= link_to @topic.user.username, @topic.user %>
							</span>
							<%= "posted #{time_ago_in_words(@topic.created_at)} ago. #{pluralize(@topic.comments_count, "comment")}. " %>
							<% if @topic.user == current_user %>
								<%= link_to "Edit", edit_topic_path %> |
								<%= link_to "Delete", @topic,
								 															method:  :delete,
						                                  confirm: "You sure?",
						                                  title:   @topic.title %>
							<% end %>
							
						</div>
					</td>
				</tr>
			</tbody>
		</table>
	</div>
  <div class="inner topic-content"><%= generate_markdown(@topic.content) %>  </div>
</div>

<% if !@comments.empty? %>
	<div class="rect">
		<div class= "inner bottomborder">
			<h4><%= "#{@topic.comments_count} comments" %></h4>
		</div>
		<div class="h-inner">
			<%= render partial: 'comments/comment', collection: @comments, locals: { page: @page } %>
			<%= will_paginate @comments %>			
		</div>
	</div>
<% end %>

<% if signed_in? %>
	<%= render 'comments/comment_form' %>
<% end %>