config/routes.rb
CoderXCoder::Application.routes.draw do
  
  devise_for :users
  resources :users
  resources :profiles
  
  resources :notifications
  
  resources :users do
    resources :topics
    resources :notifications
    resources :comments
  end
  
  resources :topics do
    resources :comments
  end  
  
  root to: 'static_pages#home'  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:authentication_keys => [:login]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :login, :username, :email, :password, :password_confirmation, :remember_me, :profile_attributes
  
  attr_accessor :login
  USERNAME_REGAX = /\A[a-z0-9_]{3,15}/i
  validates :username, presence: true, format: { with: USERNAME_REGAX }, uniqueness: { case_sensitive: false } 
  
  has_one :profile, dependent: :destroy
  accepts_nested_attributes_for :profile
  has_many :topics, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :notifications, class_name: "Notification", foreign_key: "receiver_id"
  
  before_create :create_profile
    
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    login = conditions.delete(:login)
    where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.strip.downcase }]).first
  end
   
  def created_topics
    self.topics.order('created_at DESC')
  end

  def commented_topics
    topic_ids = self.comments.uniq.collect(&:topic_id)
    Topic.where(id: topic_ids).order('created_at DESC')
  end
  
  def unread_topic_count
    self.notifications.where(read: false).count
  end
  
  private
      
    def create_profile
      self.build_profile if self.profile.nil?
    end    
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, :except => :show
  
  def new
    @user = User.new
  end
    
  def show
    @user = User.find(params[:id])
    @created_topics = @user.created_topics.paginate(page: params[:page])
    @commented_topics = @user.commented_topics.paginate(page: params[:page])
    @user.build_profile unless @user.profile.present?
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
  
  def gravatar_for(user, options = { :size => 48 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}.png?size=#{size}"
    image_tag(gravatar_url, width:"#{size}px", height:"#{size}px")  
  end

  def header_gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}.png?size=20"
    image_tag(gravatar_url, class: "gravatar-header")  
  end
  
  
  def current_user?(user)
    user == current_user
  end
  
end

app/views/users/_user_form.html.erb
<%= form_for(@user) do |f| %>

	<%= render 'shared/error_messages', :object => f.object %>

	<%= f.label :name %>
	<%= f.text_field :name, class: "input-field" %><br />
	<%= f.label :email %>
	<%= f.text_field :email, class: "input-field" %><br />				
	<%= f.label :password %>
	<%= f.password_field :password, class: "input-field" %><br />
	<%= f.label :password_confirmation, "Confirmation" %>
	<%= f.password_field :password_confirmation, class: "input-field" %><br /><br />
	<%= f.submit submit_button_title, :action => "update", class: "btn btn-primary btn-large", 
	             style: "width: 330px" %>
<% end %>

app/views/users/_usersform.html.erb
<%= form_for(@user) do |f| %>

	<%= render 'shared/error_messages', :object => f.object %>

	<%= f.label :name %>
	<%= f.text_field :name, class: "input-xlarge input-signup" %><br />
	<%= f.label :email %>
	<%= f.text_field :email, class: "input-xxlarge input-signup" %><br />				
	<%= f.label :password %>
	<%= f.password_field :password, class: "input-xxlarge input-signup" %><br />
	<%= f.label :password_confirmation, "Confirmation" %>
	<%= f.password_field :password_confirmation, class: "input-xxlarge input-signup" %><br /><br />
	<%= f.submit submit_button_title, class: "btn btn-primary btn-large", 
	             style: "width: 330px" %>
<% end %>

app/views/users/edit.html.erb
<%= provide :title, "Account" %>

<div class="rect">
	<h3>Edit Account</h3>
	<hr />
	<div class="span-signup">
		<%= render partial: "user_form", locals: { submit_button_title: "Save account changes" } %>
	</div>
</div>

app/views/users/show.html.erb
<%= provide(:title, @user.username) %>

<% profile = @user.profile %>

<div class="rect">	
	<div class="inner bottomborder">
		<table>
			<tbody>
				<tr>
					<td width="80px">
						<div class="gravatar">
							 <%= gravatar_for(@user) %>
						</div>
					</td>
					<td>
						<h1>
							<span><%= @user.username %></span>
						</h1>
					</td>
					
					<td width="800px", align="right">
						<strong>
						<% if @user == current_user %>
							<%= link_to "Edit Profile",edit_profile_path(@user.profile), class: "btn" %>
						<% end %>
						</strong>
					</td>
				</tr>
			</tbody>
		</table>
	</div>	
	

	<% if !profile.realname.blank? || !profile.location.blank? || !profile.company.blank? || !profile.blog.blank? || !profile.github.blank? ||
		!profile.twitter.blank? || !profile.weibo.blank? || !profile.bio.blank? %>
		<div class="h-inner profile-list bottomborder">
			<dl>
				<% if !profile.realname.empty? %>
					<dt>Real Name</dt>
					<dd><%= profile.realname %></dd>
				<% end %>

				<% if !profile.location.empty? %>
					<dt>Location</dt>
					<dd><%= profile.location %></dd>
				<% end %>

				<% if !profile.company.empty? %>
					<dt>Company</dt>
					<dd><%= profile.company %></dd>
				<% end %>

				<% if !profile.blog.empty? %>
					<dt>Blog</dt>
					<dd><%= link_to profile.blog, profile.blog,target: "_blank" %></dd>
				<% end %>

				<% if !profile.github.empty? %>
					<dt>GitHub</dt>
					<dd><%= link_to profile.github, "https://github.com/#{profile.github}", 
					target: "_blank" %></dd>
				<% end %>

				<% if !profile.twitter.empty? %>
					<dt>Twitter</dt>
					<dd><%= link_to "@#{profile.twitter}", "https://twitter.com/#{profile.twitter}", target: "_blank" %></dd>
				<% end %>

				<% if !profile.weibo.empty? %>
					<dt>Weibo</dt>
					<dd><%= link_to "@#{profile.weibo}", "http://weibo.com/#{profile.weibo}", target: "_blank" %></dd>
				<% end %>			
			</dl>
		</div>
		
		<% if !profile.bio.empty? %>
			<div class="inner bio"><%= profile.bio %></div>
		<% end %>
	<% else %>
		<div class="inner bio"> 
			<% if current_user?(@user) %>
				You have not set up your profile yet!
			<% else %>
				This guy have not set up his profile yet!
			<% end %>
		</div>		
	<% end %>
</div>

<% if @user.topics.any? %>
<div class="rect">
	<div class="inner bottomborder">
		<h3><%= "#{@user.username}'s topics" %></h3>
	</div>
	
	<ul class="v-inner">
		<%= render partial: 'topics/created_topic', collection: @created_topics %>
	</ul>
	<%= will_paginate @created_topics %>
</div>
<% end %>

<% if @user.comments.any? %>
<div class="rect">
	<div class="inner bottomborder">
		<h3><%= "#{@user.username}'s comments" %></h3>
	</div>
	
	<ul class="v-inner">
		<%= render partial: 'topics/commented_topic', collection: @commented_topics %>
	</ul>
	<%= will_paginate  @commented_topics %>
</div>
<% end %>