config/routes.rb
CoderXCoder::Application.routes.draw do
  
  devise_for :users
  resources :users
  resources :profiles
  
  resources :notifications
  
  resources :users do
    resources :topics
    resources :notifications
    resources :comments
  end
  
  resources :topics do
    resources :comments
  end  
  
  root to: 'static_pages#home'  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    coderXcoder by Levey
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "Coder x Coder", root_path, :class  =>  "brand" %>
			<nav>
				<ul class="nav pull-left">
					<li><%= link_to "Topics", topics_path %></li>
				</ul>
				<ul class="nav pull-right">
					<% if signed_in? %>					
					
						<li id="fat-menu" class="dropdown">
		            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
									<%= header_gravatar_for current_user %> <%= current_user.username %><b class="caret"></b>
		            </a>
							<ul class="dropdown-menu">
								<% c = current_user.unread_topic_count %>
								<% if c > 0 %>
									<li><%= link_to "Notifications(#{c})", notifications_path %></li>
								<% else %>
									<li><%= link_to "Notifications", notifications_path %></li>
								<% end %>
								
								<li><%= link_to "Profile", current_user %></li>
	 							<li><%= link_to "Account", edit_user_registration_path(current_user) %></li>
	              <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
							</ul>
						</li>
					<% else %>
						<li><%= link_to "Sign in", new_user_session_path %></li>
						<li><%= link_to "Sign up", new_user_registration_path %></li>
					<% end %>
				</ul>					
			</nav>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= generate_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<link rel="icon" href="<%= asset_path("favicon.png") %>" />
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |key, value| %>
		<div class="alert alert-<%= key %>"><%= value %> </div>
		<% end %>
		<%= yield %>
		<div class="footer">
			<span class="grayfont link">Created by 
				<a href="http://www.slyfairy.com/" title="SlyFairy" target="_blank">SlyFairy</a>
				 ♥ For Xcoders 				
			</span>
		</div>
 	  <!-- <%= debug(params) if Rails.env.development? %> -->
	</div>	
	
</body>
</html>